version: '3'

services:
#  api:
#    container_name: api
#    build: .
#    ports:
#      - "5000:5000"
#    environment:
#     - NODE_ENV=local
#     - ES_HOST=elasticsearch
#     - PORT=3000
#     - DBX_APP_KEY=5q28gt6qyndwadq
#     - DBX_APP_SECRET=nt7vu3ycirob5db
#     - TIKA_CLIENT_ONLY=true
#     - TIKA_SERVER_ENDPOINT=tika

  masterdb:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=masterdb
    volumes:
      - masterdb_volume:/var/lib/mysql

  elastic-node1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: elastic-node1
    environment:
      - node.name=elastic-node1
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elastic-node2,elastic-node3
      - cluster.initial_master_nodes=elastic-node1,elastic-node2,elastic-node3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data_node1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
#    networks:
#      - elastic
  elastic-node2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: elastic-node2
    environment:
      - node.name=elastic-node2
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elastic-node1,elastic-node3
      - cluster.initial_master_nodes=elastic-node1,elastic-node2,elastic-node3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data_node2:/usr/share/elasticsearch/data
#    networks:
#      - elastic
  elastic-node3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: elastic-node3
    environment:
      - node.name=elastic-node3
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elastic-node1,elastic-node2
      - cluster.initial_master_nodes=elastic-node1,elastic-node2,elastic-node3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data_node3:/usr/share/elasticsearch/data
  tika:
    image: apache/tika:latest
    container_name: tika
    ports:
      - 9998:9998

    #
    #  frontend: # Nginx Server For Frontend App
    #    container_name: cs-frontend
    #    image: nginx
    #    volumes: # Serve local "public" dir
    #      - ./public:/usr/share/nginx/html
    #    ports:
    #      - "8080:80" # Forward site to localhost:8080

volumes:
  elastic_data_node1:
    driver: local
  elastic_data_node2:
    driver: local
  elastic_data_node3:
    driver: local
  masterdb_volume:
    driver: local

