"""Files model

Revision ID: 026e44c9aabe
Revises: 80dbd4ae96d9
Create Date: 2021-06-15 16:16:46.884563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026e44c9aabe'
down_revision = '80dbd4ae96d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=1023), nullable=False),
    sa.Column('filepath', sa.String(length=2047), nullable=False),
    sa.Column('content_store_id', sa.String(length=255), nullable=False),
    sa.Column('last_synced_on', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=63), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
