"""column name changes in files model

Revision ID: 9fa15d1fad55
Revises: b8958e2c6606
Create Date: 2021-06-22 16:10:43.740912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9fa15d1fad55'
down_revision = 'b8958e2c6606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('last_sync_status', sa.String(length=63), nullable=True))
    op.drop_column('files', 'sync_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('sync_status', mysql.VARCHAR(length=63), nullable=True))
    op.drop_column('files', 'last_sync_status')
    # ### end Alembic commands ###
