"""Files model update with provider id

Revision ID: b6e75ca62c05
Revises: e3720cc16d3b
Create Date: 2021-06-15 18:08:20.781944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e75ca62c05'
down_revision = 'e3720cc16d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('provider_file_id', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'provider_file_id')
    # ### end Alembic commands ###
