"""File Content Mapping Model user id

Revision ID: b8958e2c6606
Revises: 5d8878007a70
Create Date: 2021-06-21 18:55:16.032705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8958e2c6606'
down_revision = '5d8878007a70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_content_mappings', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_content_mappings', 'user_id')
    # ### end Alembic commands ###
